cc.Class({
    extends: cc.Component,

    properties: {
        isSelf:false,
    },
    start () {
    },
    setScoreNumImage:function(imgNum){
        var imgName = "" ;
        if(this.isSelf == true){
            imgName = "Nums/0to9blue/" + imgNum;//是自己的话，就用蓝色数字
        }
        else {
            imgName = "Nums/0to9red/" + imgNum;//是对手的话，就用红色数字
        }
        var self = this;
        cc.loader.loadRes(imgName, cc.SpriteFrame, function (err, spriteFrame) {
            self.node.getComponent(cc.Sprite).spriteFrame = spriteFrame;
        });
    },
});
